feature: Entity 초기 설정
zolling-paper/backend pull request #2
Opened 2024-12-25 12:40 UTC by masonkimseoul

# 구현 목적
앞으로의 구현에 필요한 엔티티를 정의합니다.
Board 생성, 조회, Paper 생성, 단건 조회, 다건 조회 API를 구현합니다.

# 구현 내용
POST /board
Request
```json
{
    "name" : "mason",
    "password" : "asdf",
    "showDate" : "2025-01-01T00:00:00"
}
```
POST /paper
Request
```json
{
    "boardId" : "1",
    "name" : "mason",
    "content" : "hi"
}
```
---
GET /board/{board-id}
Response
```
{
    "id": 1,
    "name": "mason",
    "showDate": "2025-01-01T00:00:00"
}
```
GET /paper/{paper-id}
Response
```
{
    "paperId": 1,
    "createdAt": "2024-12-25T21:39:20.554825",
    "name": "mason",
    "content": "hi"
}
```
GET /board/{board-id}/papers
Response
```
{
    "responses": [
        {
            "paperId": 1,
            "createdAt": "2024-12-25T21:39:20.554825",
            "name": "mason",
            "content": "hi"
        }
    ]
}
```
# 고려사항
1. `GET /board/{board-id}/papers` API의 경우 현재 `PaperController`에 위치하고 있습니다. API 엔드포인트를 보면 `BoardController`라고 생각이 되긴 하는데, 응답하는 자원이 `PaperDetailResponses`라서 일단은 `PaperController`로 설정했습니다. 의견 부탁드립니다.
2. `Board`와 `Paper`의 도메인에서 name과 password를 하위 도메인이나 엔티티로 분리하는 것을 고려중입니다. MVP에서는 필요하지 않은 기능이라 배포 때 까지는 현행을 유지하려고 생각하고 있습니다. 이 또한 의견 부탁드립니다.

# 향후 진행 방향
예외 처리와 테스트 코드 작성이 진행 중입니다. 24년 12월 27일까지 완료하도록 하겠습니다.

2024-12-26 05:27 UTC, Minjoo522 requested changes
안녕하세요, 메이슨!
초기 세팅 고생했습니다.
몇 가지 컨벤션 궁금한 사항과 제안 남깁니다!
앞으로 컨벤션을 메이슨 방식으로 맞추기 위해서 RC를 날리오니 참고해주세요 ㅎㅎ

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/controller/BoardController.java
> +        return ResponseEntity.created(URI.create("/board/" + boardId.toString())).build();
```suggestion
        Long boardId = boardService.saveBoard(request);
        return ResponseEntity.created(URI.create("/board/" + boardId)).build();
```

`toString()` 없이도 가능한데 사용한 이유가 있을까요?

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/domain/Board.java
> +    @NotNull
데이터베이스에서는 nullable하고 애플리케이션 레벨에서만 not null을 의도하신게 맞는지 궁금합니다.

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/dto/BoardSaveReponse.java
> +public record BoardSaveReponse() {
```suggestion
public record BoardSaveResponse() {
```

오타 발견! 🧐
이 레코드는 추후 사용을 위해 미리 만들어 놓은 것일까요?

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/service/BoardService.java
> +@Service
`@Transactional`은 아직 필요하지 않다고 생각하여 적용하지 않으신 걸까요?
저는 단순한 작업을 진행하는 메서드에도 `@Transactional`을 사용하고 클래스 상단에 선언하는 편인데(이유: 애플리케이션 단에서는 하나의 일만 하는 것처럼 보이지만 내부에서는 많은 작업을 할 수도 있음 + 누락 방지), 메이슨은 어떤 방식을 선호하시나요?

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/service/BoardService.java
> +    }
두 줄 이상이면 리턴 전에 한 줄 띄는 컨벤션으로 이해하면 될까욥?

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/global/domain/BaseTimeEntity.java
> +    private LocalDateTime createdAt;
구현 클래스에서 createdAt과 updatedAt 정보가 필요한 경우 메서드를 호출해야 할 것 같은데 접근제어자를 protected로 변경하는 건 어떨까요?

2024-12-26 05:27 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/paper/service/PaperService.java
> +        return new PaperDetailResponse(paper.getId(), paper.getCreatedAt(), paper.getName(), paper.getContent());
레코드 내부에서 정적 팩토리 메서드 통해 인스턴스를 생성하는 방법은 어떻게 생각하시나요?
이 방식으로 하면 파이프 라이닝으로 깔끔하게 뺄 수 있을 것 같습니다!

```suggestion
        return boardRepository.findById(boardId)
                .map(BoardDetailResponse::of)
                .orElseThrow();
```

2024-12-26 05:31 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/board/controller/BoardController.java
> +        return ResponseEntity.created(URI.create("/board/" + boardId.toString())).build();
이전 명세는 UUID를 사용하는 것이었는데, 해당 구현 과정에서 작성해두고 수정하지 않은 것 같습니다. toString은 제거하도록 하겠습니다. 감사합니다!

2024-12-26 05:35 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/board/domain/Board.java
> +    @NotNull
앗 아닙니다. 검증 로직이 아직 없어서 혼란을 드린 것 같네요. DB에서도 nullable은 허용하지 않을 칼럼입니다.

2024-12-26 05:37 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/domain/Board.java
> +    @NotNull
그러면 `@Column(nullable = false)`를 사용하는 게 좋을 것 같아요!
제가 알기로는 `@NotNull` 어노테이션은 애플리케이션 단의 null만 검증한다고 하네요!

2024-12-26 05:41 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/board/dto/BoardSaveReponse.java
> +public record BoardSaveReponse() {
오타가 있었군요 👀 잡아주셔서 감사합니다.
며칠 전에 말씀하셨던 내용을 적용해보고자 만들어봤습니다.
생성 api 의 반환값을 void로 할 것인지, 생성에 성공한 값을 반환할 것인지 고민을 잠깐 해보았는데요, 어떤 방안이 더 좋을까요?

2024-12-26 05:54 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/board/service/BoardService.java
> +@Service
저는 굳이 @Transactional이 필요하지 않은 부분엔 달지 않으려고 해요. 필요한 메서드에만 달아서 의도를 보여주는게 조금 더 좋다고 생각했습니다.
+) 또한 아직 고려하지 않은 부분이기도 합니다 ㅎㅎ...

2024-12-26 05:56 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/board/service/BoardService.java
> +    }
넵! 이런 컨벤션 어떤가요?
다만 10줄 정도로 길어지는 메서드의 경우 붙여쓰려고 합니다.

2024-12-26 05:57 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/board/domain/Board.java
> +    @NotNull
오 감사합니다! 놓쳤던 내용이었어요.

2024-12-26 06:04 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/global/domain/BaseTimeEntity.java
> +    private LocalDateTime createdAt;
👍 도메인 내에서 사용할 때 일관성 확보를 위해 protected로 변경하겠습니다!

2024-12-26 06:25 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/board/dto/BoardSaveReponse.java
> +public record BoardSaveReponse() {
저는 생성에 성공한 값을 반환하는 걸 선호하는 편이긴한데 어떤 방식이든 괜찮습니다!

2024-12-30 07:14 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/paper/exception/PaperErrorCode.java
> +    NOT_FOUND(BAD_REQUEST, "해당 편지가 존재하지 않습니다."),
니가 뭘 알아

2024-12-30 07:18 UTC, masonkimseoul commented
마지막 리뷰 이후 커밋 기록 [편하게 보기](https://github.com/zolling-paper/backend/pull/2/files/4f4476d7b3c2719eb3a2474d22845082e5f6a533..c7c0c89a63e36b44c6c84b292c05e5f8ea228a00)

지난번에 논의했던 것처럼 생성 성공 시 생성한 값을 반환할 수 있도록 응답을 수정하였습니다.
또한 RestAssured로 테스트 코드를 작성했습니다.
궁금한 점이나 논의할 점이 있다면 알려주세요.

2024-12-30 11:13 UTC, Minjoo522 requested changes
메이슨 고생하셨습니다~
몇 가지 확인 필요한 부분이 있어 RC 날립니다 😭

2024-12-30 11:13 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/global/exception/GlobalExceptionHandler.java
> +                .body(response.getErrorMessage());
둘이 완전 같은 역할을 하는데 `BoardException`들의 상위 Exception(RuntimeException을 상속 받는) 추상 메서드를 만들어서 상속받으면 메서드 하나로 해결할 수 있을 것 같습니다.
현재 상태로는 도메인이 추가될 때마다 ExceptionHandler도 추가해줘야하네요.
그리고 `BoardException`, `PaperException`도 global 패키지에 있는 게 조금 어색하게 느껴집니다.

2024-12-30 11:13 UTC, Minjoo522 commented on src/test/java/com/zollingpaper/backend/global/DatabaseCleaner.java
> +    }
```java
    private void truncate() {
        em.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
        getTruncateQueries().forEach(query -> em.createNativeQuery(query).executeUpdate());
        em.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();

    }

    private List<String> getTruncateQueries() {
        String sql = """
                SELECT Concat('TRUNCATE TABLE ', TABLE_NAME, ' RESTART IDENTITY', ';') AS q
                FROM INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = 'PUBLIC'
                """;

        return em.createNativeQuery(sql).getResultList();
    }
```

이런식으로 만들면 중복을 없앨 수 있습니다!

2024-12-30 11:13 UTC, Minjoo522 commented on src/test/java/com/zollingpaper/backend/board/controller/BoardControllerE2ETest.java
> +    int serverPort;
```suggestion
private int serverPort;
```

접근제어자 private으로 해도 될 것 같습니다!

2024-12-30 11:13 UTC, Minjoo522 commented on src/test/java/com/zollingpaper/backend/paper/controller/PaperControllerE2ETest.java
> +    int serverPort;
```suggestion
private int serverPort;
```

접근제어자 private으로 해도 괜찮을 것 같습니다!

2024-12-31 05:03 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/paper/exception/PaperErrorCode.java
> +    NOT_FOUND(BAD_REQUEST, "해당 편지가 존재하지 않습니다."),
저는 요청한 자원을 찾지 못하는 원인이 어플리케이션에만 있지 않은 경우를 미리 고려해서 Not Found 대신 Bad Request를 사용하는 편입니다. 아시다시피 URI를 조회할 수 없을 때 Not Found를 사용하는데, 어플리케이션 외적인 요인으로 URI를 찾지 못하는 경우와 내적인 요인으로 찾지 못하는 경우를 분리하고 싶었습니다.

또한 아직 삭제 기능이 없어서 고려하지 않은 사항인데, Not Found는 자원의 일시 또는 영구 삭제를 반영할 수 없다고 생각해서 이 경우도 Bad Request를 사용하려고 했습니다.

리브는 Not Found를 어느 경우에 사용하시나요?

2024-12-31 05:07 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/global/exception/GlobalExceptionHandler.java
> +                .body(response.getErrorMessage());
BoardException과 PaperException은 각 도메인의 exception으로 옮기는게 좋겠네요.
제 이전 프로젝트인 총대마켓에서는 최상단 예외를 MarketException으로 정했는데, 이번 프로젝트에서는 최상단 예외의 네이밍이 애매해서 BoardException과 PaperException으로 예외를 구분했어요.

적당한 클래스명 생각나시면 추천 부탁드립니다!

2024-12-31 05:21 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/global/exception/GlobalExceptionHandler.java
> +                .body(response.getErrorMessage());
프로젝트명 + Exception 정도면 괜찮지 않을까요...

2024-12-31 05:45 UTC, masonkimseoul commented on src/test/java/com/zollingpaper/backend/global/DatabaseCleaner.java
> +    }
감사합니다.
`RESTART IDENTITY`는 Postgre에만 가능한 쿼리인줄 알았는데 H2에도 되네요!
반영 완료했습니다.

2024-12-31 05:56 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/global/exception/GlobalExceptionHandler.java
> +                .body(response.getErrorMessage());
좀 더 제너럴하게 `GlobalCustomException`으로 하겠습니다...

2024-12-31 07:23 UTC, Minjoo522 commented on src/main/java/com/zollingpaper/backend/paper/exception/PaperErrorCode.java
> +    NOT_FOUND(BAD_REQUEST, "해당 편지가 존재하지 않습니다."),
`Bad Request`를 넘기면 프론트 입장에서는 URI 형식이 잘못되지 않았나? 오인하게 될 것 같아서 해당 리소스가 없다라는 의미를 명확히 하기 위해 `Not Found`를 사용하는 편입니다!

2024-12-31 07:26 UTC, Minjoo522 approved these changes
메이슨 고생했습니다~
요청 주신 코멘트 남겼으니 확인해주세요!
PR은 Approve 하겠습니다.

2024-12-31 07:50 UTC, masonkimseoul commented on src/main/java/com/zollingpaper/backend/paper/exception/PaperErrorCode.java
> +    NOT_FOUND(BAD_REQUEST, "해당 편지가 존재하지 않습니다."),
URI 형식 오인으로 이어질 수도 있겠네요.
삭제 같은 경우는 방식의 차이보다 상태 코드의 차이를 고민해보았습니다(400으로 할 지 410으로 할 지). 말씀하신대로 그런 사항은 백엔드의 영역이라고 생각해요.
제안해주신대로 404로 설정해두겠습니다.

2024-12-31 07:56 UTC, merged